development:
  dialect: postgres
  database: apiexample_development
  user: postgres
  password: postgres
  host: db
  port: 5432
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@db:5432/apiexample_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@db:5432/apiexample_production?sslmode=disable"}}
