version: '3.5'
services:
  web:
    build:
      context: .
      target: builder
    env_file:
      - .env
    depends_on:
    - db
    volumes:
      - ./:/go/src/github.com/jcepedavillamayor/apiexample
    ports:
    - "3000:3000"
    command:  bash -c "./wait-for-it.sh db && buffalo db migrate && buffalo dev"
  db:
    image: postgres:9.6.7
    env_file:
      - .env
    ports:
    - "5432:5432"
